# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: pubsub.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import empty_pb2 as google_dot_protobuf_dot_empty__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='pubsub.proto',
  package='pubsub',
  syntax='proto3',
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\x0cpubsub.proto\x12\x06pubsub\x1a\x1bgoogle/protobuf/empty.proto\"-\n\x07Message\x12\x0f\n\x07\x63ontent\x18\x01 \x01(\t\x12\x11\n\tsender_id\x18\x02 \x01(\t\"T\n\x0ePublishRequest\x12\r\n\x05topic\x18\x01 \x01(\t\x12 \n\x07message\x18\x02 \x01(\x0b\x32\x0f.pubsub.Message\x12\x11\n\tsender_id\x18\x03 \x01(\t\"8\n\x10SubscribeRequest\x12\x15\n\rsubscriber_id\x18\x01 \x01(\t\x12\r\n\x05topic\x18\x02 \x01(\t\"3\n\x0fMessageResponse\x12 \n\x07message\x18\x01 \x01(\x0b\x32\x0f.pubsub.Message\"\x07\n\x05\x45mpty\"(\n\x0eSubscriberList\x12\x16\n\x0esubscriber_ids\x18\x01 \x03(\t\"\x1b\n\tTopicList\x12\x0e\n\x06topics\x18\x01 \x03(\t2\xf6\x01\n\rPubSubService\x12\x39\n\x07Publish\x12\x16.pubsub.PublishRequest\x1a\x16.google.protobuf.Empty\x12@\n\tSubscribe\x12\x18.pubsub.SubscribeRequest\x1a\x17.pubsub.MessageResponse0\x01\x12\x38\n\x0fListSubscribers\x12\r.pubsub.Empty\x1a\x16.pubsub.SubscriberList\x12.\n\nListTopics\x12\r.pubsub.Empty\x1a\x11.pubsub.TopicListb\x06proto3'
  ,
  dependencies=[google_dot_protobuf_dot_empty__pb2.DESCRIPTOR,])




_MESSAGE = _descriptor.Descriptor(
  name='Message',
  full_name='pubsub.Message',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='content', full_name='pubsub.Message.content', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='sender_id', full_name='pubsub.Message.sender_id', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=53,
  serialized_end=98,
)


_PUBLISHREQUEST = _descriptor.Descriptor(
  name='PublishRequest',
  full_name='pubsub.PublishRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='topic', full_name='pubsub.PublishRequest.topic', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='message', full_name='pubsub.PublishRequest.message', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='sender_id', full_name='pubsub.PublishRequest.sender_id', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=100,
  serialized_end=184,
)


_SUBSCRIBEREQUEST = _descriptor.Descriptor(
  name='SubscribeRequest',
  full_name='pubsub.SubscribeRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='subscriber_id', full_name='pubsub.SubscribeRequest.subscriber_id', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='topic', full_name='pubsub.SubscribeRequest.topic', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=186,
  serialized_end=242,
)


_MESSAGERESPONSE = _descriptor.Descriptor(
  name='MessageResponse',
  full_name='pubsub.MessageResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='message', full_name='pubsub.MessageResponse.message', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=244,
  serialized_end=295,
)


_EMPTY = _descriptor.Descriptor(
  name='Empty',
  full_name='pubsub.Empty',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=297,
  serialized_end=304,
)


_SUBSCRIBERLIST = _descriptor.Descriptor(
  name='SubscriberList',
  full_name='pubsub.SubscriberList',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='subscriber_ids', full_name='pubsub.SubscriberList.subscriber_ids', index=0,
      number=1, type=9, cpp_type=9, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=306,
  serialized_end=346,
)


_TOPICLIST = _descriptor.Descriptor(
  name='TopicList',
  full_name='pubsub.TopicList',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='topics', full_name='pubsub.TopicList.topics', index=0,
      number=1, type=9, cpp_type=9, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=348,
  serialized_end=375,
)

_PUBLISHREQUEST.fields_by_name['message'].message_type = _MESSAGE
_MESSAGERESPONSE.fields_by_name['message'].message_type = _MESSAGE
DESCRIPTOR.message_types_by_name['Message'] = _MESSAGE
DESCRIPTOR.message_types_by_name['PublishRequest'] = _PUBLISHREQUEST
DESCRIPTOR.message_types_by_name['SubscribeRequest'] = _SUBSCRIBEREQUEST
DESCRIPTOR.message_types_by_name['MessageResponse'] = _MESSAGERESPONSE
DESCRIPTOR.message_types_by_name['Empty'] = _EMPTY
DESCRIPTOR.message_types_by_name['SubscriberList'] = _SUBSCRIBERLIST
DESCRIPTOR.message_types_by_name['TopicList'] = _TOPICLIST
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

Message = _reflection.GeneratedProtocolMessageType('Message', (_message.Message,), {
  'DESCRIPTOR' : _MESSAGE,
  '__module__' : 'pubsub_pb2'
  # @@protoc_insertion_point(class_scope:pubsub.Message)
  })
_sym_db.RegisterMessage(Message)

PublishRequest = _reflection.GeneratedProtocolMessageType('PublishRequest', (_message.Message,), {
  'DESCRIPTOR' : _PUBLISHREQUEST,
  '__module__' : 'pubsub_pb2'
  # @@protoc_insertion_point(class_scope:pubsub.PublishRequest)
  })
_sym_db.RegisterMessage(PublishRequest)

SubscribeRequest = _reflection.GeneratedProtocolMessageType('SubscribeRequest', (_message.Message,), {
  'DESCRIPTOR' : _SUBSCRIBEREQUEST,
  '__module__' : 'pubsub_pb2'
  # @@protoc_insertion_point(class_scope:pubsub.SubscribeRequest)
  })
_sym_db.RegisterMessage(SubscribeRequest)

MessageResponse = _reflection.GeneratedProtocolMessageType('MessageResponse', (_message.Message,), {
  'DESCRIPTOR' : _MESSAGERESPONSE,
  '__module__' : 'pubsub_pb2'
  # @@protoc_insertion_point(class_scope:pubsub.MessageResponse)
  })
_sym_db.RegisterMessage(MessageResponse)

Empty = _reflection.GeneratedProtocolMessageType('Empty', (_message.Message,), {
  'DESCRIPTOR' : _EMPTY,
  '__module__' : 'pubsub_pb2'
  # @@protoc_insertion_point(class_scope:pubsub.Empty)
  })
_sym_db.RegisterMessage(Empty)

SubscriberList = _reflection.GeneratedProtocolMessageType('SubscriberList', (_message.Message,), {
  'DESCRIPTOR' : _SUBSCRIBERLIST,
  '__module__' : 'pubsub_pb2'
  # @@protoc_insertion_point(class_scope:pubsub.SubscriberList)
  })
_sym_db.RegisterMessage(SubscriberList)

TopicList = _reflection.GeneratedProtocolMessageType('TopicList', (_message.Message,), {
  'DESCRIPTOR' : _TOPICLIST,
  '__module__' : 'pubsub_pb2'
  # @@protoc_insertion_point(class_scope:pubsub.TopicList)
  })
_sym_db.RegisterMessage(TopicList)



_PUBSUBSERVICE = _descriptor.ServiceDescriptor(
  name='PubSubService',
  full_name='pubsub.PubSubService',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_start=378,
  serialized_end=624,
  methods=[
  _descriptor.MethodDescriptor(
    name='Publish',
    full_name='pubsub.PubSubService.Publish',
    index=0,
    containing_service=None,
    input_type=_PUBLISHREQUEST,
    output_type=google_dot_protobuf_dot_empty__pb2._EMPTY,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
  _descriptor.MethodDescriptor(
    name='Subscribe',
    full_name='pubsub.PubSubService.Subscribe',
    index=1,
    containing_service=None,
    input_type=_SUBSCRIBEREQUEST,
    output_type=_MESSAGERESPONSE,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
  _descriptor.MethodDescriptor(
    name='ListSubscribers',
    full_name='pubsub.PubSubService.ListSubscribers',
    index=2,
    containing_service=None,
    input_type=_EMPTY,
    output_type=_SUBSCRIBERLIST,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
  _descriptor.MethodDescriptor(
    name='ListTopics',
    full_name='pubsub.PubSubService.ListTopics',
    index=3,
    containing_service=None,
    input_type=_EMPTY,
    output_type=_TOPICLIST,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
])
_sym_db.RegisterServiceDescriptor(_PUBSUBSERVICE)

DESCRIPTOR.services_by_name['PubSubService'] = _PUBSUBSERVICE

# @@protoc_insertion_point(module_scope)
